# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/oscar/setup-makefiles.sh

VENDOR_DEVICE_FOLDER := vendor/pantech/oscar/proprietary

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

# Audio
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libacdbloader.so:system/lib/libacdbloader.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libaudcal.so:system/lib/libaudcal.so 

# Bins
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    $(VENDOR_DEVICE_FOLDER)/bin/bridgemgrd:system/bin/bridgemgrd \
    $(VENDOR_DEVICE_FOLDER)/bin/btnvtool:system/bin/btnvtool \
    $(VENDOR_DEVICE_FOLDER)/bin/cnd:system/bin/cnd \
    $(VENDOR_DEVICE_FOLDER)/bin/gsiff_daemon:system/bin/gsiff_daemon \
    $(VENDOR_DEVICE_FOLDER)/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(VENDOR_DEVICE_FOLDER)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(VENDOR_DEVICE_FOLDER)/bin/mpdecision:system/bin/mpdecision \
    $(VENDOR_DEVICE_FOLDER)/bin/netmgrd:system/bin/netmgrd \
    $(VENDOR_DEVICE_FOLDER)/bin/pantech_server:system/bin/pantech_server \
    $(VENDOR_DEVICE_FOLDER)/bin/port-bridge:system/bin/port-bridge \
    $(VENDOR_DEVICE_FOLDER)/bin/qmiproxy:system/bin/qmiproxy \
    $(VENDOR_DEVICE_FOLDER)/bin/qmuxd:system/bin/qmuxd \
    $(VENDOR_DEVICE_FOLDER)/bin/qseecomd:system/bin/qseecomd \
    $(VENDOR_DEVICE_FOLDER)/bin/rild:system/bin/rild \
    $(VENDOR_DEVICE_FOLDER)/bin/rmt_storage:system/bin/rmt_storage \
    $(VENDOR_DEVICE_FOLDER)/bin/thermald:system/bin/thermald \
    $(VENDOR_DEVICE_FOLDER)/bin/time_daemon:system/bin/time_daemon \
    $(VENDOR_DEVICE_FOLDER)/bin/usb_manager:system/bin/usb_manager

# Camera
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libcamera_client.so:system/lib/libcamera_client.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov8820_default_video.so:system/lib/libchromatix_ov8820_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov8820_preview.so:system/lib/libchromatix_ov8820_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov8820_video_hd.so:system/lib/libchromatix_ov8820_video_hd.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_ov8820_zsl.so:system/lib/libchromatix_ov8820_zsl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3h2_default_video.so:system/lib/libchromatix_s5k3h2_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3h2_preview.so:system/lib/libchromatix_s5k3h2_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libgemini.so:system/lib/libgemini.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmipl.so:system/lib/libmmipl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    $(VENDOR_DEVICE_FOLDER)/lib/liboemcamera.so:system/lib/liboemcamera.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    $(VENDOR_DEVICE_FOLDER)/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so

# Cnd
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libcneutils.so:system/lib/libcneutils.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libxml.so:system/lib/libxml.so

# EGL
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libC2D2.so:system/lib/libC2D2.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libgsl.so:system/lib/libgsl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libOpenVG.so:system/lib/libOpenVG.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    $(VENDOR_DEVICE_FOLDER)/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so

# Firmware
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf

# GPS
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libgps.so:system/lib/libgps.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libloc_eng.so:system/lib/libloc_eng.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libloc_ext.so:system/lib/libloc_ext.so \

# Media libraries
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmosal.so:system/lib/libmmosal.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmmparser.so:system/lib/libmmparser.so 

# Pantech_server libs
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libiw.so:system/lib/libiw.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libmtc.so:system/lib/libmtc.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libpantech_qcci.so:system/lib/libpantech_qcci.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libpantech_wifi_mac_backup.so:system/lib/libpantech_wifi_mac_backup.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libpantech_wifi_mac_rw.so:system/lib/libpantech_wifi_mac_rw.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libwcnftmp.so:system/lib/libwcnftmp.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libwcnftmpscan.so:system/lib/libwcnftmpscan.so 

# Qualcomm common libs
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libdiag.so:system/lib/libdiag.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libdsutils.so:system/lib/libdsutils.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libidl.so:system/lib/libidl.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqdi.so:system/lib/libqdi.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqdp.so:system/lib/libqdp.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmi.so:system/lib/libqmi.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqmiservices.so:system/lib/libqmiservices.so 

# Radio
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libnetmgr.so:system/lib/libnetmgr.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libqc-opt.so:system/lib/libqc-opt.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libril.so:system/lib/libril.so 

# Sensors
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so 

# Sky rild
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/lib/libsky_rawdata.so:system/lib/libsky_rawdata.so \
    $(VENDOR_DEVICE_FOLDER)/lib/libskytestclient.so:system/lib/libskytestclient.so 

# WLAN 
PRODUCT_COPY_FILES += \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/wlan/prima/WCNSS_qcom_cfg_orgi.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg_orgi.ini \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/wlan/prima/WCNSS_qcom_cfg_trptis.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg_trptis.ini \
    $(VENDOR_DEVICE_FOLDER)/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin
